platform:ios,'7.0'
pod "AFNetworking","~> 2.0"
pod "SDWebImage","~> 3.7.2"
pod "QBImagePickerController","~>2.2.2"

pod 'AMap3DMap' #3D地图SDK
#pod 'AMap2DMap' #2D地图SDK(2D地图和3D地图不能同时使用)
pod 'AMapSearch' #搜索服务SDK

pod 'Masonry'